# Generated by Django 3.2.3 on 2021-05-25 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta', '0003_usersubscribe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSubscribe',
        ),
    ]
